[package]
name = "gitless"
version = "0.1.0"
edition = "2021"

[lib]
path = "./src/lib.rs"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.14", features = ["derive"] }
git2 = "0.18.1"
thiserror = "1.0.56"
